name: Go Deploy Build And Test 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  DockertTest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Prepare
        id: prep
        run: |
          TAG=latest
          IMAGE="go-deploy"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: docker/Dockerfile.dev
          load: true
          tags: ${{ steps.prep.outputs.tagged_image }}

      - name: Run Tests 
        run: |
          docker run --rm \
              -e GEN_SSH_KEYS=1 -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -e AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }} \
              -v ${{ github.workspace }}:/go-deploytesting -w /go-deploytesting -t go-deploy:latest ./run.sh
